### ISSUE TITLE
url_for on server uses 127.0.0.1:XXXXX while url_for within tests uses www.example.com

### ISSUE THREAD

**Issue by edlebert** [teampoltergeist/poltergeist#201]
Is there a way to make the app server use what the tests use?  As of right now, I can't verify any url hosts.

**Comment by cweilemann** [comment]
+1

**Comment by twalpole** [comment]
@cweilemann  You're +1ing an issue that was closed over 3 years ago???

**Comment by cweilemann** [comment]
I'm +1ing an issue that was commented on after it was closed, and closed based on an assumption.  So, yes. :)  Would you prefer I open a new, identical issue?

**Comment by twalpole** [comment]
@cweilemann Commented on 2 years ago -- and closed based on an assumption that hasn't been proven wrong.  Do you have proof that this is an issue specific to Poltergeist (and thus caused by poltergeist) ?  (Hint - No you don't since the default_url_option host value being used is set either in the rails integration test class or in the rspec-rails gem ) -  This has nothing to do with Poltergeist.

**Comment by cweilemann** [comment]
Oh, the arrogance...  It doesn't matter. I found a work around to the issue. Regardless, poltergeist is awesome.  Keep up the good work!
