### ISSUE TITLE
HTTP Basic Authentication

### ISSUE THREAD

**Issue by mobzilla** [teampoltergeist/poltergeist#263]
We are currently working on a website that is protected by http basic authentication. We can authenticate using http://username@password:somedomain.com/path in selenium but not poltergeist. Is there any plan to add basic authentication to poltergeist?

**Comment by hiattp** [comment]
@route I'm seeing this same response (`bad URI 'Keep-Alive'`) while sending multiple headers (`Access-Token`, `Token-Type`, etc). Oddly it only happens when the test runs first or by itself. Trying to grab more of the raw request...wireshark not cooperating at the moment (what do you use to view request info like you posted above?). Running phantom 2.0.0, qt 5.4.1 and poltergeist 1.6.0.

**Comment by hiattp** [comment]
Ugh sorry never mind, I was accidentally setting cookies with newlines in them :pensive: :palm_tree:

**Comment by route** [comment]
oh ok =)
