### ISSUE TITLE
Inconsistency between #value and #text when filling and retrieving textarea content during same session

### ISSUE THREAD

**Issue by dandehavilland** [teampoltergeist/poltergeist#271]
This feels like a bug but I'm not 100% sure. I expected line 430 to pass in the same manner as 438, whereas it fails, returning an empty string. See attached failing test-case.

https://github.com/dandehavilland/poltergeist/commit/af36aa1592a318e76b51485b2df7acbffcdd6020

**Comment by aeonaut** [comment]
Same problem here, methinks. Without Poltergeist:

```
> page.find("#textarea_id").value
"default_value"
> page.find("#textarea_id").text
"default_value"
> fill_in "#textarea_id", with: 'new_value'
> page.find("#textarea_id").value 
"new_value"
> page.find("#textarea_id").text
"new_value"
```

With Poltergeist:

```
> page.find("#textarea_id").value
"default_value"
> page.find("#textarea_id").text
"default_value"
> fill_in "#textarea_id", with: 'new_value'
> page.find("#textarea_id").value 
"new_value"
> page.find("#textarea_id").text
"default_value"
```

Now the "value" and the text of the textarea are inconsistent. Fortunately, on form submission, the "value" wins; however, since the textarea doesn't actually have a value (unlike an input element), this is confusing to say the least. Cost me an hour of hair-pulling anyway.

**Comment by twalpole** [comment]
To test for multiple textarea elements on the page with capybara you should be using the have_field matcher

    expect(page).to have_field('', type: 'textarea', with: 'foo', count: 3)

**Comment by cindyward1** [comment]
My problem had nothing to do with multiple textareas on a page; I only had 1. However, the job at which I was concerned about this issue ended 6 months ago so I can't test it anymore.

**Comment by joaomilho** [comment]
Why this was closed? It's 2017 and I get the same behavior @aeonaut does.

I would expect `fill_in` to set the text in a textarea and not the value.

**Comment by cindyward1** [comment]
@joaomilho, I think I may have found the answer to our question in this StackOverflow post: [](http://stackoverflow.com/questions/18879566/capybara-can-find-but-not-fill-in) . The difference between .text() and .val() [](http://stackoverflow.com/questions/807867/difference-between-val-and-text) also helps explain this. FWIW, HTH.

**Comment by twalpole** [comment]
@joaomilho Why would you expect fill_in to set text content?  It's a form element so it fills in the value property of the element.  Go to a web page with a textarea on it in your browser, fill in some text and then use the dev console to call  `innerText` on the element, now call `value` on the element.

**Comment by joaomilho** [comment]
sure @twalpole, if that's the case, what is the expected way of setting the text of a textarea using capybara?

**Comment by twalpole** [comment]
@joaomilho Same as a text field, #fill_in or #set

**Comment by cindyward1** [comment]
@joaomilho, after 2 years, I think I finally understand this: Strictly speaking, a textarea isn't guaranteed to have text, only a value, even though this is counterintertuitive to me.

In JavaScript, we are supposed to use .text() to set/retrieve the text of HTML elements that are not inputs, e.g. <h1> or <p> or <span>. We should use .val() to set/retrieve the value of HTML elements are are inputs, e.g. <textarea> or <input>. In Capybara, we use fill_in to set the value of input elements, but we are supposed to use page.find().value to retrieve what we filled in, not page.find().text, corresponding to what we would use in JavaScript.

But this is specification must be ambiguous, so some implementers (e.g. racktest) have chosen to implement such that a textarea has text as well as value, and some implementers (e.g. poltergeist) have chosen to implement such that a textarea has only value. (One could argue that someone really should tighten up the spec one way or the other to eliminate this ambiguity, since it's confusing us.)

This also answers my original question from over 2 years ago: has_content must use .text(), not .value(), so it's not guaranteed to work. I need to remember that only a non-input element is guaranteed to has_content, and that input elements should be checked using has_value. HTH.

**Comment by twalpole** [comment]
@cindyward1 The racktest driver isn't a browser, it's a parsed html document with a few methods added to somewhat mimic what a browser would do.  As such it has no concept of element properties only element attributes, which means changes made are immediately reflected in the element source as opposed to in browsers where the properties get changed but the actual html attributes don't.  The racktest driver is only really valid for very basic tests.   With either driver you should be calling `#value` to get the current value of any form field element, any example showing using `#text` to get the current value is wrong.

**Comment by cindyward1** [comment]
@twalpole I think we're in violent agreement here :)

**Comment by twalpole** [comment]
@cindyward1 Yep :)
