### ISSUE TITLE
Not allowed to load local resource: ../application.js

### ISSUE THREAD

**Issue by alanq** [teampoltergeist/poltergeist#305]
page("#my_id").trigger('click') isn't firing the elements jQuery event handler. I'm guessing this error related to the "Not allowed to load local resource" message:
...
{"response"=>false}
{"name"=>"click", "args"=>[3, 2]}
poltergeist [1366370900594] state default -> mouse_event
poltergeist [1366370900596] state mouse_event -> loading
Not allowed to load local resource: file:///home/me/rails/my_app/public/assets_test/application.css
...
Not allowed to load local resource: file:///home/me/rails/my_app/public/assets_test/application.js

**Comment by twalpole** [comment]
Closing this due to lack of info (it's possible the last comment was cut off due to bad html escaping)

**Comment by rennietime** [comment]
I faced the same issue as the OP and this was the only reference I could find online of someone facing my exact problem. In my case it turned out to NOT be an issue with Poltergeist. One of the former devs on our team had added the following two lines of code to `test.rb`:

```
config.action_controller.asset_host = "file://#{::Rails.root}/public"
config.assets.prefix = 'assets_test'
```

Obviously, removing those lines made all my problems disappear.

Just adding the comment here in case anyone else runs into this issue.
