### ISSUE TITLE
Intermittent Capybara::Poltergeist::BrowserError in within_iframe

### ISSUE THREAD

**Issue by lawliet89** [teampoltergeist/poltergeist#373]
With the following code snippet, I get intermittent errors that are difficult to reproduce. 

```ruby
    page.within_frame('display-iframe') do
      page.should have_content('Bacon Ipsum')
    end
```

```
     Failure/Error: page.should have_content('Bacon Ipsum')
     Capybara::Poltergeist::BrowserError:
       There was an error inside the PhantomJS portion of Poltergeist. This is probably a bug, so please report it. 
       
       [object Object]
           at /home/yongwen/.rvm/gems/ruby-2.0.0-p247@typesetr/gems/poltergeist-1.3.0/lib/capybara/poltergeist/client/compiled/web_page.js:355
           at /home/yongwen/.rvm/gems/ruby-2.0.0-p247@typesetr/gems/poltergeist-1.3.0/lib/capybara/poltergeist/client/compiled/web_page.js:38
           at /home/yongwen/.rvm/gems/ruby-2.0.0-p247@typesetr/gems/poltergeist-1.3.0/lib/capybara/poltergeist/client/compiled/node.js:24
           at /home/yongwen/.rvm/gems/ruby-2.0.0-p247@typesetr/gems/poltergeist-1.3.0/lib/capybara/poltergeist/client/compiled/browser.js:157
           at /home/yongwen/.rvm/gems/ruby-2.0.0-p247@typesetr/gems/poltergeist-1.3.0/lib/capybara/poltergeist/client/compiled/browser.js:67
           at about:blank:37
           at /home/yongwen/.rvm/gems/ruby-2.0.0-p247@typesetr/gems/poltergeist-1.3.0/lib/capybara/poltergeist/client/compiled/connection.js:16
           at /home/yongwen/.rvm/gems/ruby-2.0.0-p247@typesetr/gems/poltergeist-1.3.0/lib/capybara/poltergeist/client/compiled/connection.js:1
     ....
```

I am using the latest version of phantomjs (1.9.1). Could this be a phantomjs bug?

Not sure what other details I can provide. Please let me know.

**Comment by twalpole** [comment]
Does anyone have an example which shows the issue?

**Comment by thehappycoder** [comment]
Happens for me as well and all the time -- no matter if I use sleep or find.

```
within_frame('frame') do
	    		find('input[name=Addnew]').click
	    		sleep 1

	    		within('form') do
	    			fill_in 'Mac', with: mac
	    			fill_in 'Ip', with: ip

	    			find('input[name=Save]').click
	    			sleep 5 # No matter how big the sleep is here, it's failing

		        	find('#t_title').text != 'Add or Modify an Address Reservation Entry' # Fails here
	    		end
	    	end
```

**Comment by twalpole** [comment]
@thehappycoder We need versions of poltergeist, phantomjs, and capybara you're using - as well as the debug log output to have any chance at figuring out what you have happening, however looking at your test a couple of things leap out.  

1.  rather than sleep 1 you should be doing within('a more specific selector') that uniquely identifies the form you're going to be filling in - Having a more specific selector like form#new_interface  or whatever would match would make the within wait for the new form to appear.

2.   What does your find('input[name=Save]').click cause to happen?  If it cause a new page to appear then you're no longer inside the form (potentially frame if it replaces the entire page) since it's been replaced and of course the find will fail.     

3.  find('#t_title').text != ...   is a bad way to write capybara tests since it will check the text as soon as the element is found rather than seeing if the text changes/gets replaced - you're much better off writing  find('#t_title', text: 'Add or Modify ...')

If the Save click only replaces the content of the frame (and not the entire browser page) then I'd change the test to

    within_frame('frame') do
      find('input[name=Addnew]').click
      within('form#specific_id_of_form_that_appears') do
        fill_in 'Mac', with: mac
        fill_in 'Ip', with: ip

        find('input[name=Save]').click
      end
      expect(page).to have_selector('#t_title', text: 'Add or Modify an Address Reservation Entry')
    end

**Comment by twalpole** [comment]
Closing due to lack of response
