### ISSUE TITLE
turbolinks page:load issues

### ISSUE THREAD

**Issue by cj** [teampoltergeist/poltergeist#422]
It appears rails turbolinks doesn't work correctly with poltergeist, has anyone experienced issues?  The `page:load` event is never triggered after doing `Turbolinks.visit(url)`, but testing it in a regular browser everything works as expected and `page:load` is triggered.

**Comment by rept** [comment]
Can somebody confirm this?  I had some errors on a site using turbolinks and tried to make a test first before fixing the problems.  Strange thing was, the test never failed even though I'm 100% sure it wasn't working correctly with Turbolinks.  I fixed the issue on the site and tests remained green so I think this also confirms that turbolinks isn't used?

Any reason why this is the case?

**Comment by twalpole** [comment]
Turbolinks disables itself on some browsers that don't support the features it uses -- https://github.com/rails/turbolinks/blob/master/lib/assets/javascripts/turbolinks.coffee#L700  -- I'm guessing that the phantomjs version used didn't support some of the features Turbolinks needs so it's not enabling itself.  If more info is provided and a minimal test case we can reopen and look at this.

**Comment by auctionet-mob** [comment]
Because we found this issue through Google:

We're on the "new" Turbolinks (not turbolinks-classic) and we had similar issues. We're not currently able to upgrade to latest phantomjs, so we don't know if that would fix things.

Anyway, we worked around it by running this JS early on:

```
if (navigator.userAgent.indexOf("PhantomJS") !== -1) {
  window.requestAnimationFrame = window.requestAnimationFrame || function(cb) { return setTimeout(function() { cb(0) }, 0); }
}
```

So basically, we're doing a simplistic polyfill for the function if it's missing, but only for PhantomJS. (Not for actual users with old browsers.)
