### ISSUE TITLE
keydown, keyup, keypress events are not raised on empty input

### ISSUE THREAD

**Issue by Valve** [teampoltergeist/poltergeist#437]
If I clear the input using
```
fill_in 'input', with: ''
```

this will not generate these events.

**Comment by twalpole** [comment]
Correct since the field is cleared by just setting it's value to ''  -  If you expect something else you would need to specify exactly which keypresses you expect.  You can also use #send_keys to send those keys if you wish.   PRs implementing the capybara defined driver options to be passed to fill_in/set would be considered
