### ISSUE TITLE
HTTP Cache-Control expires header respected by default in Phantomjs v2.0 leading to state "bleeding" between tests

### ISSUE THREAD

**Issue by floehopper** [teampoltergeist/poltergeist#621]
It looks to me as if `Cache-Control` headers are respected by default when using Poltergeist v1.6.0 with Phantomjs v2.0 (but not with Phantomjs v1.9.8) and I have seen this lead to browser state "bleeding" between tests. Is this the expected behaviour? It seems surprising to me. You can find more info here:

* https://github.com/alphagov/smart-answers/issues/1612
* https://github.com/alphagov/smart-answers/pull/1613

Let me know if you need more details.

/cc @tomstuart

**Comment by bradleywright** [comment]
Given they're headless browsers I'd expect them to just behave like browsers, with an option to disable it in Poltergeist as part of your test run.

**Comment by floehopper** [comment]
Perhaps this should be a Capybara issue then...? Although it would be good to know whether it was an intentional change between v1.9.8 & v2.0 and whether there is a configuration option to disable it.

**Comment by tomstuart** [comment]
An automated browser should behave like a browser *within an individual test*, but should [be reset](https://github.com/jnicklas/capybara/blob/90f5d374fda563d8457475915b4ac312a0199c9a/lib/capybara/rspec.rb#L18-L23) [between tests](https://github.com/jnicklas/capybara/blob/90f5d374fda563d8457475915b4ac312a0199c9a/lib/capybara/cucumber.rb#L7-L9) to provide isolation. If one test involves the user logging in, for example, then it would be wrong for the next test to begin in a logged-in state. In general, each test should run as though it’s the only test.

On further inspection, it’s apparent that Capybara intentionally compromises in this area. The [specification](https://github.com/jnicklas/capybara/blob/90f5d374fda563d8457475915b4ac312a0199c9a/lib/capybara/spec/session/reset_session_spec.rb) of “resetting a session” between tests ensures that cookies are cleared and that the browser is sent to a new blank page, [but](https://github.com/jnicklas/capybara/blob/90f5d374fda563d8457475915b4ac312a0199c9a/lib/capybara/session.rb#L87-L93):

> This method does not:
>
> * accept modal dialogs if they are present (Selenium driver now does, others may not)
> * **clear browser cache/HTML 5 local storage/IndexedDB/Web SQL database/etc.**
> * modify state of the driver/underlying browser in any other way
>
> as doing so will result in performance downsides and it's not needed to do everything from the list above for most apps.

So it’s a pragmatic trade-off. Capybara doesn’t require drivers to do a complete reset of all browser state, because that’s expensive and unnecessary for the majority of cases where simply cleaning out cookies is enough to make everything look fresh again.

The comment [continues](https://github.com/jnicklas/capybara/blob/90f5d374fda563d8457475915b4ac312a0199c9a/lib/capybara/session.rb#L95-L99):

> If you want to do anything from the list above on a general basis you can:
>
> * write RSpec/Cucumber/etc. after hook
> * monkeypatch this method
> * use Ruby's `prepend` method

This makes it pretty clear that, if you write tests that are sensitive to more browser state than just the cookies and page contents, it’s your responsibility to clear that state explicitly between tests.

So, given that the intentional compromise is unlikely to change, it’s not directly a Capybara or a Poltergeist problem; the “correct” solution is to use some flavour of before/after hook to tell Poltergeist to reset PhantomJS more aggressively for each cache-sensitive test. (Whether the Poltergeist API supports this is another question!)

**Comment by floehopper** [comment]
@tomstuart: Thanks. Closing.
