### ISSUE TITLE
undefined method `post' for #<Capybara::Poltergeist::Driver:0x007fe01d44fd18>

### ISSUE THREAD

**Issue by tellis9397** [teampoltergeist/poltergeist#632]
Receiving this error when running a test using poltergeist.  Using 'js: true' to try and test whether or not something appears on the page.  

I'm using:
--OS X 10.10.3
--phantomjs 2.0.0
--ruby 1.9.3
--capybara 2.0.3
--rspec-rails 2.0.0.beta.18

Any advice?

**Comment by cbatson** [comment]
@tellis9397 I'm experiencing this issue, and wondering why you closed it. Did you find a solution?

**Comment by twalpole** [comment]
@cbatson  Capybara drivers don't do post/get -- you `visit` the page you want and then interact with the page to generate any requests.  If you want to be using get/post you shouldn't be using Capybara, and probably not in a feature test.

**Comment by cbatson** [comment]
@twalpole Thanks. `Capybara::RackTest::Driver` driver responds to `post`, but `Capybara::Poltergeist::Driver` doesn't. I'll keep digging / find another way.

**Comment by twalpole** [comment]
@cbatson Yes, and it only works because the rack_test driver isn't based on a real browser. Those methods should have been deprecated a long time ago, and will most likely be gone in Capybara 3.0. You really shouldn't be calling any `session.driver.xxx` methods if you want your tests to work across multiple drivers.

**Comment by cbatson** [comment]
@twalpole Got it, thanks. Unfortunately I'm dealing with some code that violates this. I shall make it right. 😃
