### ISSUE TITLE
Poltergeist returns blank text from hidden div

### ISSUE THREAD

**Issue by githorse** [teampoltergeist/poltergeist#641]
Hiding a div (with `display: none`) seems to break retrieval of that div's text in Poltergeist/Capybara:

    > node = find('.example-div.hidden', visible: false).text
    ""

    > node = find('.example-div.visible', visible: true).text
    "same div; this text is now displayed"

This only happens with `js: true` on my test -- i.e., with Poltergeist. No issues with plain Capybara. (I can inspect the page html and verify that the text on the div is actually still there with javascript enabled; my javascript is not deleting this text from the dom somehow.)

**Comment by twalpole** [comment]
This is as designed.  From the capybara docs http://www.rubydoc.info/github/jnicklas/capybara/Capybara/Node/Element#text-instance_method , if you want it to return text that is not visible on the page you need to pass :all to the text method

    node = find('.example-div.hidden', visible: false).text(:all)

The reason you're not seeing it with "plain Capybara" (by which I assume you mean the racktest driver) is because the racktest driver doesn't process css, so it doesn't know that your 'hidden' class means the element isn't visible.  It does process display:none in a style attribute or a hidden attribute  on an element though so if you had

    node = find('.example-div[hidden]', visible: false).text 

its behavior would match poltergeist

**Comment by githorse** [comment]
Thanks @twalpole -- `text(:all)` does indeed do what I want. Still a bit confused why Rack::Test behaves differently, since it clearly knows the element is invisible (because it won't find it without the `visible: false` argument), but I'll leave that for another day.

**Comment by twalpole** [comment]
@githorse If the racktest driver really only finds the element when visible: false and still returns the full text text when called without the :all parameter that would imply a bug in Capybara.  There are tests specifically for that behavior that pass though.  If you can create a reproducible example please file an issue over in the capybara project.
