### ISSUE TITLE
Page not fully loaded after call to `visit` when using phantomjs 2.0.0

### ISSUE THREAD

**Issue by donv** [teampoltergeist/poltergeist#649]
Hi!

Great work on poltergeist!  It is of great benefit to our development and testing, every day :smile: 

We tried an upgrade to phantomjs 2.0.0 the other day, and ran into some trouble.  The most important one is a difference in timing.  It seems a call to `visit` waits until the page is fully loaded when using phantomjs 1.9.8, but returns before images are loaded when using phantomjs 2.0.0.

The effect is that screen shots taken after a call to `visit` include images when using 1.9.8, but can be without images when using 2.0.0.

Another effect is that a test will finish before all images are loaded in pages loaded by the test, leaving requests running on the server while DatabaseCleaner cleans and fixtures are being loaded.  This results in database errors and failing tests.

Is there a way to ensure pages are fully loaded before continuing after a call to `visit` when using phantomjs 2.0.0?

**Comment by donv** [comment]
Anybody able to reproduce this?

**Comment by donv** [comment]
This error is consistent for us with phantomjs 2.0.0.  Anybody else able to reproduce it?

**Comment by twalpole** [comment]
`visit` waits for phantomjs to fire its onLoadFinished event (unless it was only a hash change to the url)-- That event is described here - http://phantomjs.org/api/webpage/handler/on-load-finished.html  -  you may be better off checking at phantomjs what exactly "finished loading" means, or producing a test case for the behavior you believe is wrong, rather than repeatedly asking if anyone else can reproduce it.

**Comment by donv** [comment]
Hi @twalpole !

Thanks for the response.  It usually pays off checking if it is a known problem before putting in lots of work for a test case.  Also getting a second reproduction helps deciding if it is a local problem on my system.

I felt waiting two months before asking again when there has been no response at all was not nagging.  My mistake.

I'll check with phantomjs and see if I can produce an automated test case for it.

My current test case is based on manual inspection of any screenshot taken directly after `visit` has returned.

**Comment by twalpole** [comment]
One guess here would be you're using a polyfill for responsive images that is running in phantom 2 but not in 1.9.x because it's WebKit engine is so old. That would leave asynchronous image requests that onLoad would fire before completion.  If that is what's happening you may be out of luck and just have to put a delay before taking screenshots (or disable the polyfill when testing)

**Comment by donv** [comment]
@twalpole Thank you so much for the tip.  I will look into it and report back.

**Comment by donv** [comment]
Solved it!  It was actually not `visit` that was the subject but `click_link`.  My test called `click_link` on a JavaScript enabled link (via TurboLinks) that did an ajax call that resulted in a DOM manipulation that triggered new images to be loaded, and these images are slow to load.

I now use this method to ensure images are loaded before I take a screen shot:

```ruby
  IMAGE_WAIT_SCRIPT = <<EOF
function pending_image() {
  var images = document.images;
  for (var i = 0; i < images.length; i++) {
    if (!images[i].complete) {
        return images[i].src;
    }
  }
  return false;
}()
EOF

  def assert_images_loaded
    start = Time.now
    loop do
      pending_image = evaluate_script IMAGE_WAIT_SCRIPT
      break unless pending_image
      assert (Time.now - start) > Capybara.default_max_wait_time
      sleep 0.1
    end
  end
```

Thanks again @twalpole for you guidance.
