### ISSUE TITLE
poltergeist-phantomjs:Screenshot does not have all the objects

### ISSUE THREAD

**Issue by haridak** [teampoltergeist/poltergeist#709]
Environment
phantomjs -  2.0
Poltergeist - 1.7
Application - reactjs

In the after block, I take screenshot if the test fails. however, the screenshot when run when in the above mentioned environment gives the below file. Do you know why not all the page objects are shown and if there is a way around this? all inputs are appreciated! thanks.

![capybara-tc_number_1](https://cloud.githubusercontent.com/assets/6343552/11513660/05d6e214-983a-11e5-8ec8-a9a964f25815.png)

**Comment by twalpole** [comment]
Since your test is failing when it's taking the screenshot, I would assume an application or JS error is causing the page to not fully load.  If that's not it you'll need to provide some sort of test case showing the behavior.

**Comment by haridak** [comment]
I see an almost blank image(exactly like  the one shown above) when I take a screenshot after a test case succeeds as well. The screenshot taken with the tests are running with capybara-selenium has all the objects. I sent you the testcase. Let me know if you need any more details. thank you!

**Comment by twalpole** [comment]
It's fine to post your test in the issue - I'm adding below because there doesn't appear to be anything proprietary in it

    it '9. adds a reservation' do
      obj.searchandReserve('New York', 'CubeSmart') 
      obj.reservationDetails('Reservation', 'Nine', '99999999999', 'website', 'DNIS', '','notes for this reservation', Date.today.strftime("%m/%d/%Y"), Date.today.strftime("%m/%d/%Y"), false)
      obj.confirmPosting('Reservation', 'Nine', "", '(999) 999-9999', Date.today.strftime("%m/%d/%Y"))
      find_button('Close', disabled =false).click
    end

Where is this test actually failing?   Also, are you overriding find_button because the Capybara provided find_button takes an options hash as the second parameter not a boolean value -- maybe you meant

    find_button('Close', disabled: false).click

although the default value for disabled is false so passing it doesn't really do anything

As far as the image goes try passing the full: true option to save_screenshot, and/or use the remote debugging feature described in the README to look at the css being applied to the page

**Comment by twalpole** [comment]
Closing due to lack of response
