### ISSUE TITLE
Is there a way to make tests fail on javascript warnings?

### ISSUE THREAD

**Issue by dylankarr** [teampoltergeist/poltergeist#743]
I was wondering if there's any way to force tests to fail when javascript raises warnings (not just errors)? If so, can we add it to documentation somewhere? If not, is that a feature worth considering?

I'm working on a project using react where everyone keeps forgetting to add `key={ ... }` to array components, and I was hoping by requiring no warnings for tests to pass we could help catch those issues before they get merged.

**Comment by twalpole** [comment]
No there is no way to force that.  The issue is that javascript warning are really nothing more than console logs, and phantomjs provides no way of knowing what level the console log is.  That combined with the fact that 3rd party libraries tend to issue a few warnings every now means I don't know if it would be a useful feature (if it could be implemented somehow).  For your use case you could probably pass a StringIO object in as the :phantomjs_logger option when registering your poltergeist driver, and then do a pattern match (for the warnings you care about) on it in an after block and raise an exception if matching.
