### ISSUE TITLE
localhost refused to connect

### ISSUE THREAD

**Issue by catmando** [teampoltergeist/poltergeist#755]
I am running on mac osx, and when I try calling page.driver.debug, a chrome tab comes up pointing to localhost:9664, but chrome says "localhost refused to connect"

Any help would be much appreciated.

**Comment by ramunasm** [comment]
Same issue here, I'm on Windows.

**Comment by route** [comment]
What version do you use guys?

**Comment by ramunasm** [comment]
I'm using 1.9.0

**Comment by tansaku** [comment]
I have the same issue - on OSX el capitan and poltergeist 1.9.0

http://localhost:9664/ can't be reached

**Comment by twalpole** [comment]
What version of chrome? what version of osx? what version of phantomjs? what do you have :inspector set to your poltergeist configuration?

**Comment by catmando** [comment]
FYI... sorry for leaving this issue open, but I tracked this down to the fact that I am using Opal (ruby to javascript transpiler) which breaks chromes poltergeist driver.   The reason is that Opal adds functions to the array prototype, which chrome dislikes, so any code that you have that plays around with built in javascript types could be causing this issue (or you have a different issue completely.)

**Comment by twalpole** [comment]
Closing this since from @catmando description it sounds like it was phantomjs issue with code produced by Opal -  for anyone else still having this issue, and not running code that is modfying the array prototype -- please check which interface on your machine has port 9664 listening and whether or not that interface is what localhost resolves to.

**Comment by tansaku** [comment]
@twalpole I just updated to poltergeist 1.16 and I'm still having this issue on OSX 10.12.6 - I don't have Opal, but I just removed a `puffing_billy` proxy and it started working ...

**Comment by mjsommer** [comment]
@catmando, I am having a similar issue, and for what its worth, a work around.

Issue: remote-debugger-port=9664, but getting "This webpage is not available" on https://localhost:9664/

Workaround: Instead of waiting for https://localhost:9664/ to resolve, go directly to http://127.0.0.1:9664//webkit/inspector/inspector.html?page=2

Setup: 
phantomjs verions 2.1.1
Ubuntu 14.04.3 LTS
