### ISSUE TITLE
How to use send_keys on a hidden element?

### ISSUE THREAD

**Issue by rachel-carvalho** [teampoltergeist/poltergeist#771]
I'm trying to get a huge suite of tests to run on Poltergeist (we're currently using Selenium, but we want to cut down the time it takes to run everything). Due of some weird issues with Material Design Lite, the page is not styled 100% properly in Phantom (there are some flexbox issues going on), and so right now I'm just _always_ using `find('selector').trigger('click')`.

The problem I'm facing right now is that I need to use `find('selector').send_keys` but since the element is not initially focused, Poltergeist is trying to do it [automatically](https://github.com/teampoltergeist/poltergeist/blob/master/lib/capybara/poltergeist/client/browser.coffee#L341) with `target.mouseEvent('click')`, which breaks because the element is covered by another.

Is there a way to bypass this? Maybe this method could use `trigger` too, since it would be safer?

Thanks in advance!

**Comment by twalpole** [comment]
send_keys intentionally only sends to visible elements because a user can only send keys to visible elements - and by trying to work around these issues by sending JS created events you're circumventing that restriction.  That leads to testing the site in a way no user could use it, and therefore can lead to tests passing that really shouldn't pass.  I don't think we'll be changing this.
