### ISSUE TITLE
Capybara::Poltergeist::StatusFailError

### ISSUE THREAD

**Issue by vladra** [teampoltergeist/poltergeist#791]
Spent few days trying to fix this, read bunch of similar issues here, but still didn't manage to solve this problem.

Sometimes Poltergeist fails with StatusFailError. It is totally unpredictable, or I din't find specific reason when it happens.

```
{"id":"8b2b61e4-4ce3-428c-aa86-d75240679abd","name":"set_js_errors","args":[false]}
Fontconfig warning: ignoring UTF-8: not a valid region tag
{"command_id":"8b2b61e4-4ce3-428c-aa86-d75240679abd","response":true}
{"id":"8a0477ae-ff51-46ce-b455-bb8f0a75f529","name":"set_debug","args":[true]}
{"command_id":"8a0477ae-ff51-46ce-b455-bb8f0a75f529","response":true}
{"id":"c35716a4-580c-4ab0-818f-e9ec96ed2a1d","name":"set_url_whitelist","args":[""]}
{"command_id":"c35716a4-580c-4ab0-818f-e9ec96ed2a1d","response":true}
{"id":"4bb18446-4b7e-40d9-91ed-a2e9a515adef","name":"visit","args":["http://127.0.0.1:48696/login"]}
{"command_id":"4bb18446-4b7e-40d9-91ed-a2e9a515adef","error":{"name":"Poltergeist.StatusFailError","args":["http://127.0.0.1:48696/login",null]}}
{"id":"b78bf5ee-40e3-4426-b996-6519708d1bca","name":"network_traffic","args":[]}
{"command_id":"b78bf5ee-40e3-4426-b996-6519708d1bca","response":{"1":{"request":{"headers":[{"name":"Accept","value":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},{"name":"User-Agent","value":"Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1"}],"id":1,"method":"GET","time":"2016-06-27T16:36:04.851Z","url":"http://127.0.0.1:48696/login"},"responseParts":[],"error":null}}}

#<Capybara::Poltergeist::NetworkTraffic::Request:0x007f74e6ebc7d0 @data={"headers"=>[{"name"=>"Accept", "value"=>"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"}, {"name"=>"User-Agent", "value"=>"Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1"}], "id"=>1, "method"=>"GET", "time"=>"2016-06-27T16:36:04.851Z", "url"=>"http://127.0.0.1:48696/login"}, @response_parts=[], @error=nil>

{"id":"0a6277e4-092e-4232-8f1a-0575cced7d57","name":"reset","args":[]}
{"command_id":"0a6277e4-092e-4232-8f1a-0575cced7d57","response":true}

Capybara::Poltergeist::StatusFailError:         Capybara::Poltergeist::StatusFailError: Request to 'http://127.0.0.1:48696/login' failed to reach server, check DNS and/or server status
```

My poltergeist config is:

```
Capybara.register_driver :poltergeist do |app|
  Capybara::Poltergeist::Driver.new(
    app,
    js_errors: false,
    inspector: WENV['INSPECTOR'] || false,
    phatomjs_options: ['--load-images=no', '--ignore-ssl-errors=yes'],
    timeouts: 60
  )
end
```

Also I'm doing `page.driver.browser.url_whitelist = ['']` and `Capybara.reset_sessions!` like other issues here suggested.

Phantomjs version 2.1.1
Poltergeist version 1.9.0
Rails 5 and Minitest.

Until now error happened only on the CircleCI. Didn't encounter anything similar locally yet

All the time error happens during login step. If login is passed, I never see this error (about 50 failed test runs). I've disabled all js there and it has no images and external dependencies. We have font from google servers, but whitelist driver settings is dealing with it I think (at least I don't see it in network traffic).

Any tips how to solve this? Thanks in advance

**Comment by twalpole** [comment]
This error means the server failed to send a response (in time). Is it always the first test that fails? (If so that's usually because of the time it takes to compile assets - and can usually be worked around by increasing timeout or precompiling assets). Looking at your config `timeouts: 60` is not a valid config option, it should be `timeout: 60`  (no s) - as documented [here](https://github.com/teampoltergeist/poltergeist#customization).  
I'm not sure what you're hoping to configure with `page.driver.browser.url_whitelist = ['']` since that would substring match any url which is the default.  If after fixing your option you still have issues please post your apps test.log showing the requests and responses for the failing test.

**Comment by vladra** [comment]
Omg, what a dumb typo. I hope this will fix my issue. Will start testing.

If it is related to assets compilation, maybe I should try to precompile assets before running test.

Related to `url_whitelist = ['']` - I thought that if I'm specifying whitelist, I'm blacklisting all that is not there. So it should blacklist all outgoing connections. (like `block_unknown_urls` in Capybara Webkit). It seems it should be.

**Comment by twalpole** [comment]
@vladra  url_whitelist entries are substring matched to the requested url -- an empty string would match every url (since an empty string is a substring of any other string) and therefore you're allowing all urls.  Poltergeist 1.10.0 released this morning adds a few features around url_white/blacklist - the ability to register default white/blacklists in your driver registrations (which survive session reset so you don't have to set for every test if they're not changing) and interpretation of wildcard syntax in the urls.

**Comment by vladra** [comment]
I've tried to increase timeout time to 120s, but it still didn't work for me.

Then I've tried to reconfigure my tests to precompile assets ahead, before tests are run. And this solved my issue completely.

So I can confirm that this issue was because of assets compile time.

Thanks for help

**Comment by jmuheim** [comment]
> Then I've tried to reconfigure my tests to precompile assets ahead, before tests are run. And this solved my issue completely.

@vladra how did you configure this?

**Comment by vladra** [comment]
@jmuheim I'm not using rails right now, so don't remember exactly the options. But you can configure rails to not compile assets in test env. And then do precompilation in a regular way for test env before any feature test are run.

So your commands to run tests on CI could look like this for example:
- rake assets:precompile
- rspec
