### ISSUE TITLE
textContent should be allowed for non SVGElement elements

### ISSUE THREAD

**Issue by nunopato** [teampoltergeist/poltergeist#792]
Poltergeist 1.10.0 (1.9.0 works just fine)

The change https://github.com/teampoltergeist/poltergeist/commit/7a187ae833c6bdc968467da1f04627cdffd5efb9#diff-893b71c0619c86f7b1058a9e9875af42R172 introduced what I think it's an undesirable behaviour. `textContent` should be allowed for non `SVGElement` as well. There are other side effects when not using `textContent` other than just "Elements with no visible children should not return any text "(https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent)

1.9.0

```
[1] pry(#<RSpec::ExampleGroups::TransferringProjects::ForATransferToAPersonalAccount>)> select = all('.-members select').first
=> #<Capybara::Node::Element tag="select" path="//HTML[1]/BODY[1]/DIV[1]/DIV[1]/SECTION[2]/DIV[2]/DIV[1]/FORM[1]/TABLE[1]/TBODY[1]/TR[1]/TD[5]/SELECT[1]"> 
[2] pry(#<RSpec::ExampleGroups::TransferringProjects::ForATransferToAPersonalAccount>)> select.text
=> "option 1 option2"
```

1.10.0

```
[1] pry(#<RSpec::ExampleGroups::TransferringProjects::ForATransferToAPersonalAccount>)> select = all('.-members select').first
=> #<Capybara::Node::Element tag="select" path="//HTML[1]/BODY[1]/DIV[1]/DIV[1]/SECTION[2]/DIV[2]/DIV[1]/FORM[1]/TABLE[1]/TBODY[1]/TR[1]/TD[5]/SELECT[1]">
[2] pry(#<RSpec::ExampleGroups::TransferringProjects::ForATransferToAPersonalAccount>)> select.text
=> ""
```

The latter returns an empty string even though the element itself (select) and non of it's descendants (option) are hidden.

**Comment by twalpole** [comment]
Hmmm -- this is changed behavior and I'm not entirely sure which should be considered correct, since option elements aren't technically visible on the page, so we need to look into this.  In the meantime, what are you using the text for?  If it's for checking that specific options exist, thats what Capybara provides the `option` selector for, so something like

    select = all('.-members select').first
    expect(select).to have_selector(:option, 'option 1').and have_selector(:option, 'option 2')

or

    expect(select).to match_selector(:select, nil, options: ['option 1', 'option 2'])

(of course it's possible this behavior change has broken that too, although I'm pretty sure it's tested in the capybara test suite which poltergeist passes)

**Comment by twalpole** [comment]
@nunopato You can also call  select.text(:all) to get the text you got previously (that ends up calling textContent)

**Comment by nunopato** [comment]
@twalpole thanks for your reply.

I think we have different interpretations of what means for an element to be hidden. Having the hidden property is NOT the same as not being visible at a given point in time.

To add to that, if you refer to the mozilla article I mentioned above, on the 'Differences from innerText' section, you will find the following sentence `innerText is aware of style and will not return the text of hidden elements, whereas **textContent** will.`...

```
document.getElementById('select_902541641')
<select id=​"select_902541641">​…​</select>​

document.getElementById('select_902541641').textContent
"option1 option2 option3"

document.getElementById('select_902541641').innerText
""
```

If the goal here is to closely match the DOM API, then this behaviour should be changed.

@twalpole wdyt ?

**Comment by twalpole** [comment]
@nunopato I am not talking about the hidden property anywhere,  when I say hidden I mean not currently  visible on the page - whether that is through display:none, hidden property, or potentially non-dropped selecto boxes.  I'm also not sure why you're arguing about the differences between the definitions of textContent and innerText.  We know the differences, and if you really want textContent then pass :all to the capybara `text` method which will then always call textContent.   Also claiming 1.9.0 works fine really isn't an argument, since 1.9 could have been wrong, and in fact was definitely wrong for an element that contained only other elements that were non visible on the page (hence the change)

The goal here is not to match a DOM API - it is to comply with the Capybara Element#text definition - http://www.rubydoc.info/github/jnicklas/capybara/Capybara/Node/Element#text-instance_method - which is meant to basically track the webdriver spec https://w3c.github.io/webdriver/webdriver-spec.html#get-element-text definition- which basically says that by default it should return only visible text and "This is equivalent to calling element.innerText".  The only question here is whether or not option elements in a visible select should be considered visible on the page or not for the purpose of getting text.  Selenium (generally considered the capybara driver to emulate in cases of confusion about what something actually means) does return the option text for selects that are visible on the page - however it also returns the text for options that have a style of "display:none" even though they aren't ever shown on the page, so it's not really correct behavior either.  This is something that needs further thought/investigation.

**Comment by twalpole** [comment]
@route Thoughts?

**Comment by route** [comment]
@twalpole sorry was on vacation, hm this is difficult let me think...
