### ISSUE TITLE
Cannot simulate shift-click on a checkbox

### ISSUE THREAD

**Issue by airblade** [teampoltergeist/poltergeist#811]
I am trying to simulate shift-clicking a checkbox but I can't figure out how.

I have tried the following in my Capybara code:

```ruby
my_checkbox.native.send_key [:Shift, :Click]
my_checkbox.native.send_key [:Shift, :Space]
my_checkbox.native.send_key [:Shift, ' ']
```

Unfortunately they all act like a plain `click`.

Any help would be appreciated!

I'm using Poltergeist 1.9.0 and phantomjs 2.1.1.

**Comment by twalpole** [comment]
my_checkbox.send_key (there is no need for .native anymore - the README needs updating) emulates keypresses not mouse clicks, and there is no support for specifying modifiers with #click so there is currently no way to do a shift-click .  If you have a keyboard only alternative for whatever JS is handling your shift-click you could use that, otherwise you may not be able to test this behavior (without using execute_script to build and fire off your own events)

**Comment by airblade** [comment]
Thanks for the information!
