### ISSUE TITLE
PhantomJS v2.1.1.0 - Could not find an executable 'phantomjs' that matched the requirements '>= 1.8.1', '< 3.0' - Cliver::Dependency::VersionMismatch

### ISSUE THREAD

**Issue by Sam-Levene** [teampoltergeist/poltergeist#819]
Hi Team,

I recently updated to PhantomJS 2.1.1.0. and have run into this error while attempting to run my code using poltergeist

Could not find an executable 'phantomjs' that matched the requirements '>= 1.8.1', '< 3.0'. Found versions were {"C:/Ruby23-x64/bin/phantomjs.BAT"=>"23"}

Please Note: I am using a Windows laptop and my ruby setup is as follows:

Ruby => ruby 2.3.0p0 (2015-12-25 revision 53290) [x64-mingw32]
RubyGems => 2.6.7
Gem List => 
 - phantomjs (2.1.1.0)
 - poltergeist (1.10.0)

Thanks

**Comment by twalpole** [comment]
@Sam-Levene  What is the output of running C:/Ruby23-x64/bin/phantomjs.BAT ??

**Comment by yaauie** [comment]
@Sam-Levene it appears as though the only executable `phantomjs` that is on your `PATH` is `C:/Ruby23-x64/bin/phantomjs.BAT`, and when it is executed with a solitary `--version` flag, we're parsing out `23` as the first number (which coincidentally is part of the path to the `.BAT` file).

Can you run the following from your command line?
~~~
C:\Ruby23-x64\bin\phantomjs.BAT --version
~~~
or
~~~
phantomjs --version
~~~

If the executable is in fact a supported version, you can force the version detection library to not verify it by setting the [`CLIVER_NO_VERIFY` environment variable](https://github.com/yaauie/cliver#get-out-of-my-way-cliver).

**Comment by twalpole** [comment]
@yaaui  Very very sorry -- I went to delete my comment and somehow ended up deleting yours instead - could you please repost

**Comment by twalpole** [comment]
This was originally posted by @yaauie  but I somehow accidentally deleted it

@Sam-Levene it appears as though the only executable phantomjs that is on your PATH is C:/Ruby23-x64/bin/phantomjs.BAT, and when it is executed with a solitary --version flag, we're parsing out 23 as the first number (which coincidentally is part of the path to the .BAT file).

Can you run the following from your command line?

C:\Ruby23-x64\bin\phantomjs.BAT --version
or

phantomjs --version
If the executable is in fact a supported version, you can force the version detection library to not verify it by setting the CLIVER_NO_VERIFY environment variable.

**Comment by route** [comment]
Oh sorry didn't notice he was running a bat file. Then it's not the issue

**Comment by Sam-Levene** [comment]
Trying the `C:\Ruby23-x64\bin\phantomjs.BAT --version` gave the following issue: 

![cmd](https://cloud.githubusercontent.com/assets/19433453/19637622/ecdaa9b8-99c7-11e6-8c97-24d08a63d530.PNG)

and `phantomjs --version` gave: "'phantonjs' is not recognized as an internal or external command,
operable program or batch file." despite having PhantomJS installed on my computer. Not sure why it's saying not recognised.

**Comment by yaauie** [comment]
It looks like you're using the [`phantomjs-binaries'](https://github.com/avaynshtok/phantomjs-binaries) gem, and have a  `phantomjs.BAT` on your [`PATH`](https://en.wikipedia.org/wiki/PATH_(variable)) pointing to it.

Unfortunately, `phantomjs-binaries` doesn't support Windows; it uses the [`uname`](https://github.com/avaynshtok/phantomjs-binaries/blob/master/bin/phantomjs#L9) syscall (which is not on Windows by default) to detect which of the pre-built binaries to select, but even then, it only provides 64-bit builds for linux & darwin.

You will need to install phantomjs [normally](http://phantomjs.org/download.html#windows) and [add it to your `PATH`](http://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/) so that command-line programs (like `poltergeist`) can find it.

**Comment by Sam-Levene** [comment]
Nevermind. Please Close. 

Fixed using a Ubuntu VM without having to worry about all of this crap on Win 7 x64
