### ISSUE TITLE
There's no API for page refresh/reload

### ISSUE THREAD

**Issue by vemv** [teampoltergeist/poltergeist#876]
Hi!

There's no API for refreshing the current page. PhantomJs seems to support it.

Can we have it?

Cheers - Victor

**Comment by route** [comment]
@twalpole hm don't remember if we have it in capybara, is it worth adding?

**Comment by twalpole** [comment]
It's not in Capybara, andI'm not really convinced it is worth adding.  When testing an app needing to refresh the page would generally be a sign of a bad UI.  I'm open to being convinced otherwise with a decent use case, but I can't think of one right now.  If one does really need to reload the page it's as easy as `visit(current_url)`

**Comment by vemv** [comment]
it's not built-in in the Capybara, but e.g. selenium-webdriver has it. Also, seemingly Phantom has it, so it might be a cheap addition.

Reloading can be useful in integration tests as it can assert certain bugs don't happen ("when I reload, state xyz is lost"). Obviusly I don't expect my users to use the refresh button as part of the UX

**Comment by Gaelan** [comment]
I'm using Capybara to scrape another site, so refreshing is useful for that.

**Comment by twalpole** [comment]
https://github.com/teampoltergeist/poltergeist/pull/898
