### ISSUE TITLE
Setting 'port' option has no impact

### ISSUE THREAD

**Issue by drewB** [teampoltergeist/poltergeist#886]
When I pass in a 'port' option to Driver.new it has no impact.  I still see a random port when looking at current_url.

```
Capybara.register_driver :poltergeist do |app|
  opts = {
    :port => 67789543   
  }

  Capybara::Poltergeist::Driver.new(app, opts)
end
```

**Comment by twalpole** [comment]
Possibly, because the port number you show is completely invalid??  - Also this is the specifying the port that Poltergeist will communicate to the PhantomJS process it starts on, nothing to do with the port it will load a site from, is that the port you're expecting it to change?  If it is please show how you know it's not on the correct port.

**Comment by drewB** [comment]
Re invalid port, my mistake.  See the same results will valid ones.  That is helpfully to hear it is the port that communicates with PhantomJS.  As you suggested, I am looking to set the port that the rails server is running on.  We have a client side redirect that needs the full URL so want to make them consistent.  Can you point me to how I would accomplish that?

**Comment by drewB** [comment]
N/M.  I see I need to use Capybara.server_port - <port>.  Thanks for your help.
